[package]
name = "typocase"
version = "0.1.0"
authors = ["Martin Tovmassian <martin.tovmassian@protonmail.com>"]
edition = "2018"
description = "CLI for translating string into typography conventions."
license = "MIT"

[dependencies]
